import type { WebOrder } from "./types";

export const DUMMY_ORDERS: WebOrder[] = [
  {
    id: "wo1",
    reference: "WO-1001",
    date: "25 Jul 2026, 10:42",
    status: "pending",
    paymentStatus: "unpaid",
    paymentMethod: "cod",
    grandTotal: 259.98,
    customer: {
      name: "Ayla Mammadova",
      email: "ayla@example.com",
      phone: "+994 50 123 4567",
    },
    shipping: {
      address: "Nizami küç. 45, Apt 8",
      city: "Baku",
      country: "Azerbaijan",
      postalCode: "AZ1000",
      notes: "Please ring the bell twice.",
    },
    items: [
      { name: "Wireless Headphones", qty: 1, price: 129.99 },
      { name: "Running Shoes", qty: 1, price: 89.99 },
      { name: "Yoga Mat", qty: 1, price: 39.99 },
    ],
  },
  {
    id: "wo2",
    reference: "WO-1002",
    date: "24 Jul 2026, 15:08",
    status: "confirmed",
    paymentStatus: "paid",
    paymentMethod: "epoint",
    grandTotal: 129.99,
    customer: {
      name: "Elchin Huseynov",
      email: "elchin@mail.az",
      phone: "+994 55 987 6543",
    },
    shipping: {
      address: "Əliağa Vahid küç. 12",
      city: "Ganja",
      country: "Azerbaijan",
      postalCode: "AZ2000",
    },
    items: [{ name: "Wireless Headphones", qty: 1, price: 129.99 }],
  },
  {
    id: "wo3",
    reference: "WO-1003",
    date: "23 Jul 2026, 09:31",
    status: "shipped",
    paymentStatus: "paid",
    paymentMethod: "epoint",
    grandTotal: 349.97,
    customer: {
      name: "Sara Aliyeva",
      email: "sara.ali@gmail.com",
      phone: "+994 70 456 7890",
    },
    shipping: {
      address: "Rasul Rza 88, Block B",
      city: "Sumqayit",
      country: "Azerbaijan",
      postalCode: "AZ5000",
    },
    items: [
      { name: "Smart Watch", qty: 1, price: 199.99 },
      { name: "Fitness Tracker", qty: 1, price: 89.99 },
      { name: "Phone Stand", qty: 1, price: 59.99 },
    ],
  },
  {
    id: "wo4",
    reference: "WO-1004",
    date: "22 Jul 2026, 18:20",
    status: "completed",
    paymentStatus: "paid",
    paymentMethod: "cod",
    grandTotal: 89.99,
    customer: {
      name: "Kamran Quliyev",
      email: "kamran@example.com",
      phone: "+994 51 234 5678",
    },
    shipping: {
      address: "İstiqlaliyyət küç. 3",
      city: "Baku",
      country: "Azerbaijan",
      postalCode: "AZ1010",
    },
    items: [{ name: "Running Shoes", qty: 1, price: 89.99 }],
  },
  {
    id: "wo5",
    reference: "WO-1005",
    date: "21 Jul 2026, 11:55",
    status: "cancelled",
    paymentStatus: "refunded",
    paymentMethod: "epoint",
    grandTotal: 199.99,
    customer: {
      name: "Nigar Rzayeva",
      email: "nigar@outlook.com",
      phone: "+994 77 654 3210",
    },
    shipping: {
      address: "Hüsü Hacıyev 7",
      city: "Baku",
      country: "Azerbaijan",
      postalCode: "AZ1005",
      notes: "Leave at the door.",
    },
    items: [{ name: "Smart Watch", qty: 1, price: 199.99 }],
  },
  {
    id: "wo6",
    reference: "WO-1006",
    date: "20 Jul 2026, 14:02",
    status: "completed",
    paymentStatus: "paid",
    paymentMethod: "epoint",
    grandTotal: 479.96,
    customer: {
      name: "Tural Babayev",
      email: "tural.b@company.az",
      phone: "+994 50 111 2233",
    },
    shipping: {
      address: "Atatürk prospekti 22",
      city: "Baku",
      country: "Azerbaijan",
      postalCode: "AZ1073",
    },
    items: [
      { name: "Wireless Headphones", qty: 2, price: 129.99 },
      { name: "Smart Watch", qty: 1, price: 199.99 },
      { name: "Phone Stand", qty: 1, price: 59.99 },
    ],
  },
];
